### ISSUE TITLE
Missing `data` Directory on Fresh Clone.

### ISSUE THREAD

**Issue by zrc210** [clubhouse/project-analytics#1]
This is a super minor issue, but for the less technically inclined, it can introduce unnecessary barriers.

On a fresh clone, the `data` directory does not exist.

Executing `node fetch.js all` results in the following top-level exception:

```
Fetching projects...
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'data/projects.js'
    at Object.fs.openSync (fs.js:582:18)
    at Object.fs.writeFileSync (fs.js:1301:33)
    at saveProjectsToFile (/.../project-analytics/fetch.js:210:6)
    at Request._callback (/.../project-analytics/fetch.js:254:5)
    at Request.self.callback (/.../project-analytics/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (/.../project-analytics/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
```

The `README.md` should be updated to include the step to create the directory. Or better yet, the repository should include the empty directory, with a `.gitignore`.

**Comment by promethean** [comment]
I ran into the same issue
